name: This is name
run-name: This is run-name
on: [push]
jobs: 
    build:
        runs-on: ubuntu-latest
        steps:
            - name: This is first step name
              run: echo "Hello World" 
            - name: See Github Action
              run: echo "${{toJson(github)}}"
            