name: Run all Tests
run-name: Run all test cases
on: [push,workflow_dispatch]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-node@v4
          with:
            node-version: 20
        - name: Node version
          run: npm v
        - run: npm ci
        - run: npm run test
